import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import { redirect } from "next/navigation";
import { ProtectedHeader } from "../components/ProtectedHeader";
import NavMenu from "../components/NavMenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProtectedLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();

  if (!session || !session.user) {
    redirect(`/api/auth/signin`);
  }

  return (
    <div className="flex">
      <NavMenu />
      <main className="w-full">
        <ProtectedHeader />
        <div className="p-4">{children}</div>
      </main>
    </div>
  );
}
