import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Roboto } from "next/font/google";
import { Avatar } from "@/components/Avatar";
import { Header } from "@/components/Header";
import { MyHeader } from "@/components/MyHeader";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <MyHeader /> */}
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
