import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PublicHeader } from "../components/PublicHeader";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PublicLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();

  if (session && session?.user) {
    // redirect(`/dashboard`);
  }

  return (
    <div className=" min-h-screen">
      <PublicHeader />

      <main className="max-w-7xl p-9 mx-auto bg-gray-50">{children}</main>
    </div>
  );
}
